@extends('layouts.dashboard')
@section('title', 'Instructor Dashboard')
@section('page-title', 'Dashboard')
@section('user-name', 'Instructor')
@section('sidebar')@include('components.instructor-sidebar')@stop
@section('content')
<div class="space-y-6">
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div class="bg-white rounded-xl shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs text-heading/50 font-semibold uppercase tracking-wider">Total Students</p><p class="text-2xl font-bold text-heading mt-1">1,256</p></div><div class="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary"><i class="ri-group-line text-xl"></i></div></div></div>
        <div class="bg-white rounded-xl shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs text-heading/50 font-semibold uppercase tracking-wider">Total Courses</p><p class="text-2xl font-bold text-heading mt-1">18</p></div><div class="w-12 h-12 rounded-xl bg-secondary/10 flex items-center justify-center text-secondary"><i class="ri-book-open-line text-xl"></i></div></div></div>
        <div class="bg-white rounded-xl shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs text-heading/50 font-semibold uppercase tracking-wider">Total Enrolled</p><p class="text-2xl font-bold text-heading mt-1">845</p></div><div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center text-green-600"><i class="ri-user-add-line text-xl"></i></div></div></div>
        <div class="bg-white rounded-xl shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs text-heading/50 font-semibold uppercase tracking-wider">Total Revenue</p><p class="text-2xl font-bold text-heading mt-1">$28,450</p></div><div class="w-12 h-12 rounded-xl bg-red-100 flex items-center justify-center text-red-500"><i class="ri-money-dollar-circle-line text-xl"></i></div></div></div>
    </div>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div class="bg-white rounded-xl shadow-sm p-6"><h3 class="font-bold text-heading mb-4">Recent Enrollments</h3><div class="space-y-3">@for($i=1;$i<=4;$i++)<div class="flex items-center gap-3 py-2 border-b border-gray-50 last:border-0"><img src="https://placehold.co/40x40/5F3EED/FFFFFF?text=U{{ $i }}" class="w-10 h-10 rounded-full"><div class="flex-1 min-w-0"><p class="font-semibold text-heading text-sm">User {{ $i }}</p><p class="text-xs text-heading/50">Enrolled in Course {{ $i }}</p></div><span class="text-xs text-heading/40">{{ $i }}d ago</span></div>@endfor</div></div>
        <div class="bg-white rounded-xl shadow-sm p-6"><h3 class="font-bold text-heading mb-4">Revenue Overview</h3><div class="flex items-end justify-between h-32 gap-2 pt-4">@for($i=1;$i<=6;$i++)<div class="flex-1 flex flex-col items-center gap-1"><div class="w-full bg-primary/20 rounded-t-lg" style="height: {{ 20 + $i * 10 }}px"></div><span class="text-xs text-heading/50">M{{ $i }}</span></div>@endfor</div></div>
    </div>
    <div class="bg-white rounded-xl shadow-sm p-6"><h3 class="font-bold text-heading mb-4">My Courses</h3><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-gray-50 text-heading/60 text-xs uppercase tracking-wider"><th class="text-left py-3 px-4 font-semibold">Course</th><th class="text-left py-3 px-4 font-semibold">Category</th><th class="text-left py-3 px-4 font-semibold">Students</th><th class="text-left py-3 px-4 font-semibold">Price</th><th class="text-left py-3 px-4 font-semibold">Status</th></tr></thead><tbody class="divide-y divide-gray-100">@for($i=1;$i<=4;$i++)<tr class="hover:bg-gray-50"><td class="py-3 px-4 font-semibold text-heading">Course Title {{ $i }}</td><td class="py-3 px-4 text-heading/70">Design</td><td class="py-3 px-4 text-heading/70">{{ 40+$i*10 }}</td><td class="py-3 px-4 text-heading/70">${{ 29.99 + $i * 10 }}</td><td class="py-3 px-4"><span class="px-3 py-1 rounded-full text-xs font-bold bg-green-100 text-green-700">Active</span></td></tr>@endfor</tbody></table></div></div>
</div>
@endsection