@extends('layouts.dashboard')
@section('title', 'Instructor Dashboard')
@section('page-title', 'Dashboard')
@section('user-name', 'Instructor')
@section('sidebar')@include('components.instructor-sidebar')@stop
@section('content')
<div class="space-y-6">
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div class="bg-white rounded-xl shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs text-heading/50 font-semibold uppercase tracking-wider">Total Students</p><p class="text-2xl font-bold text-heading mt-1">{{ $totalStudents }}</p></div><div class="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary"><i class="ri-group-line text-xl"></i></div></div></div>
        <div class="bg-white rounded-xl shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs text-heading/50 font-semibold uppercase tracking-wider">Total Courses</p><p class="text-2xl font-bold text-heading mt-1">{{ $courses->count() }}</p></div><div class="w-12 h-12 rounded-xl bg-secondary/10 flex items-center justify-center text-secondary"><i class="ri-book-open-line text-xl"></i></div></div></div>
        <div class="bg-white rounded-xl shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs text-heading/50 font-semibold uppercase tracking-wider">Total Enrolled</p><p class="text-2xl font-bold text-heading mt-1">{{ $courses->sum('enrollments_count') }}</p></div><div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center text-green-600"><i class="ri-user-add-line text-xl"></i></div></div></div>
        <div class="bg-white rounded-xl shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs text-heading/50 font-semibold uppercase tracking-wider">Active Courses</p><p class="text-2xl font-bold text-heading mt-1">{{ $courses->where('status', 'Active')->count() }}</p></div><div class="w-12 h-12 rounded-xl bg-red-100 flex items-center justify-center text-red-500"><i class="ri-money-dollar-circle-line text-xl"></i></div></div></div>
    </div>
    <div class="bg-white rounded-xl shadow-sm p-6"><h3 class="font-bold text-heading mb-4">My Courses</h3><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-gray-50 text-heading/60 text-xs uppercase tracking-wider"><th class="text-left py-3 px-4 font-semibold">Course</th><th class="text-left py-3 px-4 font-semibold">Category</th><th class="text-left py-3 px-4 font-semibold">Students</th><th class="text-left py-3 px-4 font-semibold">Price</th><th class="text-left py-3 px-4 font-semibold">Status</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($courses as $c)<tr class="hover:bg-gray-50"><td class="py-3 px-4 font-semibold text-heading">{{ $c->title }}</td><td class="py-3 px-4 text-heading/70">{{ $c->category ?? '--' }}</td><td class="py-3 px-4 text-heading/70">{{ $c->enrollments_count }}</td><td class="py-3 px-4 text-heading/70">{{ $c->price > 0 ? '$'.number_format($c->price,2) : 'Free' }}</td><td class="py-3 px-4"><span class="px-3 py-1 rounded-full text-xs font-bold {{ $c->status=='Active' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700' }}">{{ $c->status }}</span></td></tr>@empty <tr><td colspan="5" class="py-8 text-center text-heading/50 text-sm">No courses yet. <a href="/instructor/courses/create" class="text-primary font-semibold hover:underline">Create one</a></td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
